### ISSUE TITLE
This tool doesn't work with the latest magit

### ISSUE THREAD

**Issue by maindoor** [Perlmint/magit-exttool#1]
Hi,
Is this tool being maintained ? or is there anything better out there ?
I found that this tool does not open an external diff while using magit.
Where as from command line I am able to open the external tool.

Thanks.

**Comment by Perlmint** [comment]
Thanks for reporting.
I feel sorry that this is not working, but I have not maintained this tool
long ago.
I don't know any alternatives.
Sorry.

**Comment by maindoor** [comment]
Ok. I'll close this issue then.
